---
- name: Ensure packages database is up to date
  become: yes
  apt: update_cache=yes

- name: Install Redis
  apt: name=redis-server state=installed

- name: Create config file
  template: src=conf.tpl dest={{ redis.conf_path }}/{{ redis.port }}.conf
  notify: restart redis

- name: Ensure redis is started
  service: name=redis-server state=started
